#为了配置中心直接访问测试  http://localhost:2001/server-api/dev/master
info:
  name: server-api
  profile: dev
  
spring:
  application:
    name: server-api   # 对应config-server所获取的配置文件的{application}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest    

server:
  port: 7001




logging:
  file: ${spring.application.name}.log
management:
  #security:
    #enabled: true
  endpoints:
    web:
      exposure:
        include: "*"  
        
str: '{cipher}c3104e29f234274b5834f830bbffd5c05d21a8083b4934252e55a003954f3713'
